#!/bin/bash
echo "=== GitHub推送指南 ==="
echo ""
echo "第一步：生成Personal Access Token"
echo "1. 访问：https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. 选择 'repo' 权限（全选）"
echo "4. 点击 'Generate token'"
echo "5. 复制生成的令牌（只会显示一次）"
echo ""
echo "第二步：使用令牌推送"
echo "将以下命令中的 YOUR_TOKEN 替换为您的实际令牌："
echo ""
echo "git push https://gaoshunsheng:YOUR_TOKEN@github.com/gaoshunsheng/lawyer-ai.git main"
echo ""
echo "第三步：验证推送成功"
echo "访问：https://github.com/gaoshunsheng/lawyer-ai"
echo "查看是否已成功上传代码"
echo ""
echo "注意：令牌需要妥善保存，后续可以使用以下命令缓存："
echo "git config --global credential.helper store"
echo "然后正常使用 git push"
