#!/bin/bash

echo "=== 律师AI助手项目GitHub推送指南 ==="
echo ""
echo "步骤1: 生成GitHub Personal Access Token"
echo "----------------------------------------"
echo "1. 访问: https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. Token名称: lawyer-ai-push"
echo "4. 过期时间: 选择90天"
echo "5. 选择权限: 勾选 'repo' (全选)"
echo "6. 点击 'Generate token'"
echo "7. 复制生成的令牌（只会显示一次）"
echo ""
echo "步骤2: 使用令牌推送"
echo "----------------------------------------"
echo "将以下命令中的 'YOUR_ACTUAL_TOKEN' 替换为您复制的令牌："
echo ""
echo "cd /Users/gaoshunsheng/lawyer-ai"
echo "git push https://gaoshunsheng:YOUR_ACTUAL_TOKEN@github.com/gaoshunsheng/lawyer-ai.git main"
echo ""
echo "步骤3: 验证推送成功"
echo "----------------------------------------"
echo "1. 访问: https://github.com/gaoshunsheng/lawyer-ai"
echo "2. 查看是否已成功上传代码"
echo "3. 查看提交历史和文件"
echo ""
echo "步骤4: 缓存令牌（可选）"
echo "----------------------------------------"
echo "推送成功后，可以缓存令牌避免每次输入："
echo ""
echo "git config --global credential.helper store"
echo "git push origin main  # 第一次会提示输入用户名和令牌"
echo ""
echo "注意："
echo "- 令牌需要妥善保存"
echo "- 如果令牌丢失，需要重新生成"
echo "- GitHub自2021年8月起不再支持密码认证"