"""add document tables

Revision ID: a3e1f7b2c9d4
Revises: b457588c6b0a
Create Date: 2026-05-15 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a3e1f7b2c9d4'
down_revision: Union[str, Sequence[str], None] = 'b457588c6b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('variables_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_doc_type'), 'document_templates', ['doc_type'], unique=False)
    op.create_index(op.f('ix_document_templates_category'), 'document_templates', ['category'], unique=False)
    op.create_index(op.f('ix_document_templates_tenant_id'), 'document_templates', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_templates_tenant_id'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_category'), table_name='document_templates')
    op.drop_index(op.f('ix_document_templates_doc_type'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
