"""add trial tables

Revision ID: e7a3b1c2d4f5
Revises: d5f2a8e3b1c6
Create Date: 2026-05-15 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e7a3b1c2d4f5'
down_revision: Union[str, Sequence[str], None] = 'd5f2a8e3b1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial_simulations',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rounds_completed', sa.Integer(), nullable=False),
    sa.Column('dispute_focus', postgresql.JSONB(), nullable=True),
    sa.Column('strategy_report', postgresql.JSONB(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_simulations_case_id'), 'trial_simulations', ['case_id'], unique=False)
    op.create_index(op.f('ix_trial_simulations_tenant_id'), 'trial_simulations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trial_simulations_user_id'), 'trial_simulations', ['user_id'], unique=False)

    op.create_table('trial_rounds',
    sa.Column('simulation_id', sa.UUID(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('argument_strength', sa.String(length=10), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['trial_simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_rounds_simulation_id'), 'trial_rounds', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_rounds_simulation_id'), table_name='trial_rounds')
    op.drop_table('trial_rounds')
    op.drop_index(op.f('ix_trial_simulations_user_id'), table_name='trial_simulations')
    op.drop_index(op.f('ix_trial_simulations_tenant_id'), table_name='trial_simulations')
    op.drop_index(op.f('ix_trial_simulations_case_id'), table_name='trial_simulations')
    op.drop_table('trial_simulations')
    # ### end Alembic commands ###
